export const DONE = "DONE";
export const ERROR = 'ERROR';

export const LOGOUT = 'LOGOUT';
export const SIGN_IN = 'SIGN_IN';


export const MESSAGE = 'MESSAGE';
export const LOADING = "LOADING";
export const PROCESSING_REQUEST = 'PROCESSING_REQUEST';

export const EDITED = "EDITED"

export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCHING_PRODUCTS = "FETCHING_PRODUCTS";

export const ADDED_PRODUCT = "ADDED_PRODUCT";
export const ADDING_PRODUCT = "ADDING_PRODUCT";

export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCHING_PRODUCT = "FETCHING_PRODUCT";

export const EDITTED_PRODUCT = "EDITTED_PRODUCT";

export const FETCH_PRODUCT_DETAILS = "FETCH_PRODUCT_DETAILS";
export const FETCHING_PRODUCT_DETAILS = "FETCHING_PRODUCT_DETAILS";



export const FETCH_AGERANGE = 'FETCH_AGERANGE';


export const EDITING_PRODUCT_CATEGORY = "EDITING_PRODUCT_CATEGORY"

export const ADDED_PRODUCT_CATEGORY = 'ADDED_PRODUCT_CATEGORY';
export const ADDING_PRODUCT_CATEGORY = 'ADDING_PRODUCT_CATEGORY';

export const FETCH_PRODUCT_TAG = "FETCH_PRODUCT_TAG";

export const FETCH_PRODUCT_CATEGORY = "FETCH_PRODUCT_CATEGORY";
export const FETCHING_PRODUCT_CATEGORY = "FETCHING_PRODUCT_CATEGORY";

export const FETCH_PRODUCT_CATEGORIES = "FETCH_PRODUCT_CATEGORIES";
export const FETCHING_PRODUCT_CATEGORIES = "FETCHING_PRODUCT_CATEGORIES";

export const DELETED_PRODUCT = "DELETED_PRODUCT"
export const DELETED_PRODUCT_CATEGORY = "DELETED_PRODUCT_CATEGORY"
